name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: checkout
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install dependencies
        run: yarn
